import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const appShell = readFileSync("src/components/AppShell.tsx", "utf8");
const authPage = readFileSync("src/pages/Auth.tsx", "utf8");
const settingsPage = readFileSync("src/pages/Settings.tsx", "utf8");
const card = readFileSync("src/components/Card.tsx", "utf8");
const css = readFileSync("src/index.css", "utf8");
const authRoute = readFileSync("server/routes/auth.ts", "utf8");
const apiClient = readFileSync("src/lib/api.ts", "utf8");
const middleware = readFileSync("server/middleware/auth.ts", "utf8");
const usersRoute = readFileSync("server/routes/users.ts", "utf8");
const tenancy = readFileSync("server/utils/tenancy.ts", "utf8");
const seed = readFileSync("server/seed.ts", "utf8");
const storeModel = readFileSync("server/models/Store.ts", "utf8");
const dashboardPage = readFileSync("src/pages/Dashboard.tsx", "utf8");
const managementPage = readFileSync("src/pages/Management.tsx", "utf8");
const serverIndex = readFileSync("server/index.ts", "utf8");
const resetTokenModel = readFileSync("server/models/LoginResetToken.ts", "utf8");
const roleProfiles = readFileSync("server/models/RoleProfiles.ts", "utf8");
const storeRoute = readFileSync("server/routes/stores.ts", "utf8");
const storeDatabaseUtils = readFileSync("server/utils/storeDatabases.ts", "utf8");
const packageJson = readFileSync("package.json", "utf8");

assert.ok(appShell.includes('minRole: "Employee" as Role'), "settings should be available from normal employee navigation");
assert.ok(appShell.includes('/auth/logout'), "logout should revoke the current backend session");
assert.ok(authPage.includes("Public self-signup is disabled"), "auth page should explain managed account creation");
assert.equal(authPage.includes("Demo Accounts"), false, "production auth page should not show demo account buttons");
assert.ok(settingsPage.includes("Login Security"), "settings should expose active login sessions");
assert.ok(settingsPage.includes("Notifications"), "settings should expose notification preferences");
assert.ok(settingsPage.includes("Change Password"), "settings should let the owner change their password");
assert.ok(card.includes("min-w-0"), "cards should be allowed to shrink on mobile layouts");
assert.ok(css.includes("overflow-x: hidden"), "global layout should prevent page-wide horizontal overflow");
assert.ok(authRoute.includes("UserSession.create"), "login should create server-side sessions");
assert.ok(authRoute.includes('/forgot-password'), "auth should expose a secure password reset request flow");
assert.ok(authRoute.includes('/reset-password'), "auth should expose a secure password reset completion flow");
assert.ok(authRoute.includes('/password'), "auth should expose authenticated password changes");
assert.ok(authRoute.includes("Invalid username/email or password."), "login errors should mention username/email credentials");
assert.ok(apiClient.includes('path === "/auth/login"'), "login 401s should not be rewritten as expired-session errors");
assert.ok(middleware.includes("UserSession.findOne"), "authenticated requests should validate server-side sessions");
assert.ok(middleware.includes("Owner: 3"), "owner role should outrank store roles");
assert.ok(storeModel.includes("ownerAdmin"), "stores should be first-class tenant records");
assert.ok(storeModel.includes("monthlySubscriptionPrice"), "stores should track subscription pricing");
assert.ok(storeModel.includes("paymentStatus"), "stores should track payment status");
assert.ok(storeModel.includes("databaseName"), "stores should point to a dedicated store database");
assert.ok(dashboardPage.includes("UPS Store Portfolio"), "owner dashboard should be a UPS Store portfolio");
assert.ok(dashboardPage.includes("Database:"), "owner dashboard should show each store database name");
assert.ok(managementPage.includes("Create New UPS Store"), "owner management should create store tenants and admins");
assert.ok(managementPage.includes("Delete Store"), "owner management should be able to delete stores");
assert.ok(dashboardPage.includes("Delete Store"), "owner dashboard should be able to delete stores");
assert.ok(storeRoute.includes('router.delete("/:id"'), "stores API should expose owner-only store deletion");
assert.ok(storeRoute.includes("UserSession.deleteMany"), "store deletion should revoke deleted store user sessions");
assert.ok(storeRoute.includes("dropStoreDatabase"), "store deletion should drop the dedicated store database");
assert.ok(storeDatabaseUtils.includes("bootstrapStoreDatabase"), "store database helper should create miniature per-store databases");
assert.ok(storeDatabaseUtils.includes("storeprofile"), "store database helper should seed store profile data");
assert.ok(appShell.includes("ownerNavItems"), "owner navigation should be explicit instead of inheriting employee operations");
assert.ok(serverIndex.includes("blockOwnerStoreOperations"), "owner tokens should not access store-operation APIs");
assert.ok(tenancy.includes("storeFilter"), "routes should use shared store scoping helpers");
assert.ok(usersRoute.includes("Only the platform owner can create store administrators."), "store admins must be owner-created only");
assert.ok(usersRoute.includes("Owner accounts can only create administrators and managers."), "owner should not create employee accounts directly");
assert.ok(resetTokenModel.includes("tokenHash"), "password reset tokens must be stored hashed");
assert.ok(roleProfiles.includes("AdminProfile"), "admins should have a separate profile collection");
assert.ok(roleProfiles.includes("ManagerProfile"), "managers should have a separate profile collection");
assert.ok(roleProfiles.includes("OwnerProfile"), "owners should have a separate profile collection");
assert.ok(seed.includes("SEED_DEMO_DATA"), "demo account seeding should require an explicit flag");
assert.ok(packageJson.includes("create:temp-store"), "temporary Store 8099 admin script should be available");
assert.ok(packageJson.includes("bootstrap:store-dbs"), "store database bootstrap script should be available");

console.log("finalization tests passed");
